### ISSUE TITLE
Support Front Matter with different opening and closing fences

### ISSUE THREAD

**Issue by maxkueng** [wooorm/remark-frontmatter#2]
In the [documentation for Hugo](https://gohugo.io/content-management/front-matter/) there's an example for JSON-formatted Front Matter which looks like this:

```
{
    "title": "spf13-vim 3.0 release and new website",
    "description": "spf13-vim is a cross platform distribution of vim plugins and resources for Vim.",
    "tags": [ ".vimrc", "plugins", "spf13-vim", "vim" ],
    "date": "2012-04-06",
    "categories": [
        "Development",
        "VIM"
    ],
    "slug": "spf13-vim-3-0-release-and-new-website"
}

# Title

Content
```

But this type of front matter uses only one instead of three marker characters for the fences, and the opening and closing fences aren't the same. So currently it can't be implemented as a custom "Matter" with just the `marker` property.

If there was a way to specify the full opening and closing string for the fence it would allow creating more different types of Front Matter, including JSON.

I was thinking something like this:

```js
{
  type: 'json',
  openingFence: '{',
  closingFence: '}',
}
```

or:

```js
{
  type: 'custom',
  openingFence: '<<<',
  closingFence: '>>>',
}
```

For backwards compatibility specifying just a `marker` could internally translate into ``openingFence = `${marker}${marker}${marker}` `` and ``closingFence = `${marker}${marker}${marker}` ``

For example:

```js
{
  type: 'yaml',
  marker: '-',
}
```

would become:

```js
{
  type: 'yaml',
  openingFence: '---',
  closingFence: '---',
}
```

**Comment by wooorm** [comment]
I’d accept a PR for this, depending on how much code it adds. I think it will result in more than a few lines though, which I’m not too happy about.

About backward compatibility you mentioned: I think YAML and TOML are still the most used ones, so we should optimise for that. How about, supporting marker as an object: `{open: '{', close: '}', repeat: false}`?

**Comment by maxkueng** [comment]
> How about, supporting marker as an object: {open: '{', close: '}', repeat: false}?

That sounds cool too. It would at least support the use cases I mentioned in the previous comment.

What do you think of 
 - `{open: '{', close: '}', repeat: 1}` for `{ ... }`
 - `{open: '<', close: '>', repeat: 2}` for `<< ... >>`

**Comment by wooorm** [comment]
#### HTML

`<!-- ... -->` could be supported like this right?

```js
{open: '<!--', close: '-->', repeat: false}
```

#### `repeat: number`

We can support `repeat: number`, but for this issue itself `repeat: true` (for `3`) and `repeat: false` is enough. I’m 🤷‍♂️ to whether this should be added with this issue: either option is fine.

#### another alternative

`Matter` now supports something like `{type, marker: string}`, we’re proposing adding support for `marker` to be an object (`Marker`) as well: `{open: string, close: string}`.

So we’re going with `{type, marker: string | Marker}`,

Instead of adding `repeat` to that `Marker` object, we can also add support for `{type, marker: string | Marker, fence: string | Fence}`, where `fence` is a string or object like `Marker`, but does not get automatically repeated.

Technically that means that passing `marker` gets turned into a repeated `fence` internally.

So:

```js
// this:
{type: 'toml', marker: '+'}
// equals:
{type: 'toml', marker: {open: '+', close: '+'}}
// equals:
{type: 'toml', fence: '+++'}}
// equals:
{type: 'toml', fence: {open: '+++', close: '+++'}}

**Comment by maxkueng** [comment]
All the solutions you've proposed support my use cases. I'd be more than okay with either of those. I would like to add support for JSON Front Matter in [vmd](https://github.com/yoshuawuyts/vmd) and I'm already using your module for YAML and TOML support. 
Just tell me how you'd like to have it and I'll try to make a pull request.

**Comment by wooorm** [comment]
Sweet, thank you! In that case, I like my last 'fence' proposal, you agree?

**Comment by maxkueng** [comment]
Okay cool. So...

```js
{type: 'toml', marker: '+'}
{type: 'toml', marker: {open: '+', close: '+'}}
{type: 'toml', fence: '+++'}}
{type: 'toml', fence: {open: '+++', close: '+++'}}
```

they all end up being `opening fence: +++` and `closing fence: +++`

**Comment by wooorm** [comment]
Yeah!
